Repository OrangeClassTeacher/2023-Simple-Transit, pull requests merged in 2023-05, with the labels that each got.

#49 swipe bar
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Bottomsheet/index.tsx
  frontend/src/components/Bottomsheet/style.module.css
  frontend/src/components/Input/index.tsx
  frontend/src/components/Layout.tsx
  frontend/src/components/ListGroup/index.tsx
  frontend/src/components/Map.tsx
  frontend/src/components/Meta.tsx
  frontend/src/components/Navbar.tsx
  frontend/src/components/Stepper/index.tsx
  frontend/src/components/TestCom.tsx
  frontend/src/pages/LightPage/index.tsx
  frontend/src/pages/People/index.tsx
  frontend/src/pages/ZenlyPage/index.tsx
  frontend/src/pages/_app.tsx
  frontend/src/pages/_document.tsx
  frontend/src/pages/api/hello.ts
  frontend/src/pages/index.tsx
  frontend/src/styles/globals.css
  frontend/src/styles/style.module.css
  frontend/tailwind.config.js
Labels: documentation

#50 User modal
  frontend/src/components/Layout.tsx
  frontend/src/components/Navbar.tsx
  frontend/src/components/UserModal.tsx
  frontend/src/pages/page1/index.tsx
  frontend/src/styles/globals.css
Labels: documentation

#58 44 landing page css
  frontend/src/components/Bottomsheet/index.tsx
  frontend/src/components/Input/index.tsx
  frontend/src/components/Layout.tsx
  frontend/src/components/Map.tsx
  frontend/src/pages/_app.tsx
  frontend/src/utils/Context.tsx
Labels: documentation

#61 added traffic rendering
  frontend/src/components/Layout.tsx
  frontend/src/components/Map.tsx
  frontend/src/components/Navbar.tsx
Labels: documentation

#64 Log funciton
  frontend/src/components/LoginModal.tsx
  frontend/src/components/Navbar.tsx
  frontend/src/components/RegisterForm.tsx
  frontend/src/components/SideMenu.tsx
  frontend/src/components/UserModal.tsx
  frontend/src/pages/People/index.tsx
  frontend/src/pages/page1/index.tsx
  frontend/src/styles/globals.css
Labels: documentation

#68 Freien ship
  frontend/src/components/FrienList.tsx
  frontend/src/components/Friend.tsx
  frontend/src/components/LoginModal.tsx
  frontend/src/components/Navbar.tsx
  frontend/src/components/RegisterForm.tsx
  frontend/src/components/UserModal.tsx
  frontend/src/pages/_app.tsx
  frontend/src/pages/page1/index.tsx
  frontend/src/utils/Context.tsx
Labels: documentation

#75 73 friends
  Backend/controllers/conn.controllers.ts
  Backend/controllers/user.controller.ts
  Backend/index.ts
  Backend/model/user.model.ts
  Backend/model/userconnection.model.ts
  Backend/routers/user.http
  Backend/routers/user.router.ts
  Backend/routers/userConn.http
  Backend/routers/userConn.router.ts
  adminpanel/.gitignore
  adminpanel/src/App.js
  frontend/src/components/Bottomsheet/index.tsx
  frontend/src/components/Bottomsheet/style.module.css
  frontend/src/components/FrienList.tsx
  frontend/src/components/Friend.tsx
  frontend/src/components/Input/index.tsx
  frontend/src/components/Layout.tsx
  frontend/src/components/ListGroup/index.tsx
  frontend/src/components/LoginModal.tsx
  frontend/src/components/Map.tsx
  frontend/src/components/Navbar.tsx
  frontend/src/components/SideMenu.tsx
  frontend/src/components/Stepper/index.tsx
  frontend/src/components/TestCom.tsx
  frontend/src/components/UserModal.tsx
  frontend/src/components/functions/findRoutes.tsx
  frontend/src/pages/_app.tsx
  frontend/src/utils/Context.tsx
Labels: bug, documentation

#82 81 styling
  frontend/public/marker.png
  frontend/public/my-location-icon.png
  frontend/src/components/SideMenu.tsx
  frontend/src/styles/globals.css
Labels: documentation, enhancement

#83 79 image saving location saving
  Backend/controllers/user.controller.ts
  Backend/index.ts
  Backend/package-lock.json
  Backend/package.json
  Backend/routers/user.http
  frontend/src/components/Map.tsx
  frontend/src/components/RegisterForm.tsx
  frontend/src/components/socketService.tsx
Labels: documentation

#85 81 styling
  Backend/controllers/user.controller.ts
  frontend/public/logo.png
  frontend/src/components/LoginModal.tsx
  frontend/src/components/Map.tsx
  frontend/src/components/Navbar.tsx
  frontend/src/components/RegisterForm.tsx
  frontend/src/components/SideMenu.tsx
  frontend/src/components/UserModal.tsx
  frontend/src/pages/TrafficLight/index.tsx
  frontend/src/pages/_app.tsx
  frontend/src/pages/index.tsx
  frontend/src/styles/globals.css
Labels: documentation

#88 styling
  frontend/public/clsBtn.png
  frontend/public/logo.png
  frontend/public/logo1.png
  frontend/src/components/RegisterForm.tsx
  frontend/src/components/SideMenu.tsx
  frontend/src/components/UserModal.tsx
  frontend/src/components/chatContainer.tsx
  frontend/src/components/messages.tsx
  frontend/src/pages/_app.tsx
  frontend/src/styles/globals.css
Labels: documentation
